app/home/__init__.py
from flask import Blueprint

blueprint = Blueprint(
    'home_blueprint',
    __name__,
    url_prefix='/home',
    template_folder='templates',
    static_folder='static'
)

app/home/routes.py
import copy
import json
import mritopng
import os
import requests

from flask import render_template, request, jsonify, make_response
from flask_login import login_required, current_user
from pyecharts import Gauge
from pyecharts_javascripthon.api import TRANSLATOR

from app.home import blueprint
from app import db, options, upload_path, headers
from app.base.models import InputData, OutputData


def get_options():
    option = copy.deepcopy(options)
    option.update(InputData.query.filter_by(username=current_user.username)
                  .first().get())

    output = OutputData.query.filter_by(username=current_user.username)\
        .first().get()

    # data
    # TODO(andrew j. park) 아래 링크 확인해서 세팅하
    # https://pyecharts.org/#/zh-cn/basic_charts?id=gauge%ef%bc%9a%e4%bb%aa%e8%a1%a8%e7%9b%98
    gauge = Gauge()
    gauge.add("", "", round(output['output'], 2))

    option['chart_id'] = gauge.chart_id
    option['renderer'] = gauge.renderer
    option['my_width'] = '100%'
    option['my_height'] = 600

    javascript_snippet = TRANSLATOR.translate(gauge.options)
    option['custom_function'] = javascript_snippet.function_snippet
    option['options'] = javascript_snippet.option_snippet

    return option


@blueprint.route('/index')
@login_required
def index():
    option = get_options()
    return render_template('index.html', **option)


@blueprint.route('/<template>')
@login_required
def route_template(template):
    return render_template(template + '.html')


@blueprint.route('/upload', methods=['POST'])
@login_required
def upload():
    url = os.path.join('/static/uploads', current_user.username)
    current_user_folder = os.path.join(upload_path, current_user.username)
    mri_images = dict()
    for index, (key, file) in enumerate(request.files.items()):
        if key.startswith('file'):
            file_path = os.path.join(current_user_folder, file.filename)
            file.save(file_path)
            file_name = os.path.splitext(file.filename)[0] + '.png'
            mritopng.convert_file(file_path,
                                  os.path.join(current_user_folder, file_name),
                                  auto_contrast=True)
            mri_images['mri_image_{}'.format(index + 1)] = \
                os.path.join(url, file_name)

    db.session.query(InputData).filter_by(
        username=current_user.username).update(mri_images)
    db.session.commit()

    return make_response(jsonify('success'), 200)


@blueprint.route('/push_data', methods=['POST'])
@login_required
def push_data():
    # TODO(andrew j. park) 예외 처리 추가
    data = request.get_json()
    db.session.query(InputData).filter_by(
        username=current_user.username).update({data['name']: data['value']})
    db.session.commit()

    return make_response(jsonify('success'), 200)


@blueprint.route('/predict', methods=['POST'])
@login_required
def predict():
    input_data = db.session.query(InputData).filter_by(
        username=current_user.username).first()
    response = requests.post(options['MODEL_SERVER'] + '/predict',
                             data=json.dumps(input_data.get_request_data()),
                             headers=headers)
    # TODO(andrew j. park) 예외 처리 추가
    db.session.query(OutputData).filter_by(
        username=current_user.username)\
        .update({'output': response.json()['output']})
    db.session.commit()
    print('predict : {}'.format(response.json()['output']))
    return make_response(jsonify('success'), 200)

app/home/templates/index.html
{% extends "base_site.html" %}

{% block title %} {{ title }} {% endblock title %}

{% block stylesheets %}
  {{ super() }}

  {{ dropzone.load_css() }}
  {{ dropzone.style('border: 2px dashed #0087F7; margin: 10%; min-height: 400px;') }}
{% endblock stylesheets %}

{% block content %}
  <div class="right_col" role="main">
    <br />
    <div class="row">
      <div class="col-lg-6 col-md-12 col-xs-12">
        <div class="x_panel", id="input_panel">
          <div class="x_title">
            <h2>Input</h2>
            <button type="submit" class="btn btn-success"
                    style="float: right;" onclick="submit()">Submit</button>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
            <div class="col-xs-12">
              <div class="form-group">
                <!-- GENDER -->
                <div class="col-lg-6 col-md-6 col-sd-12">
                  <label style="font-size:{{ input_title_size }}px;"> {{ gender_title }} </label>
                  <p>
                    <form name="gender_form" id="gender">
                      {% for key, value in sex.items() %}
                        <input type="radio" class="flat" name="gender"
                               id={{"gender_{}".format(key)}} value={{value}}
                               {% if sample_sex == value %}
                                 checked=""
                               {% endif %}
                        >
                        <labl style="font-size:{{ value_name_size }}px;"> {{ key }} </labl>
                        <br>
                      {% endfor %}
                    </form>
                  </p>
                </div>

                <!-- AGE -->
                <div class="col-lg-6 col-md-6 col-sd-12">
                  <label style="font-size:{{ input_title_size }}px;"> {{ age_title }} </label>
                  <p>
                    <input class="knob" id="age" data-width="100" data-height="60"
                           data-angleOffset=-90 data-angleArc=180
                           data-fgColor="#34495E" data-rotation="clockwise"
                           data-min={{ min_age }} data-max={{ max_age }}
                           value={{ sample_age }}>
                  </p>
                </div>
              </div>
            </div>

            <div class="col-xs-12">
              <div class="form-group">
                <!-- MGMT -->
                <div class="col-lg-12 col-md-12 col-sd-12">
                  <label style="font-size:{{ input_title_size }}px;"> {{ mgmt_title }} </label>
                  <p>
                    <form name="mgmt_form" id="mgmt">
                      {% for key, value in mgmt.items() %}
                        <input type="radio" class="flat" name="mgmt"
                               id={{"MGMT_{}".format(key)}} value={{value}}
                               {% if sample_mgmt == value %}
                                 checked=""
                               {% endif %}

                        >
                        <labl style="font-size:{{ value_name_size }}px;"> {{ key }}</labl>
                        <br>
                      {% endfor %}
                    </form>
                  </p>
                </div>

                <!-- IDH -->
                <div class="col-lg-12 col-md-12 col-sd-12">
                  <label style="font-size:{{ input_title_size }}px;"> {{ idh_title }} </label>
                  <p>
                    <form name="idh_form" id="idh">
                      {% for key, value in idh.items() %}
                        <input type="radio" class="flat" name="idh"
                               id={{"IDH_{}".format(key)}} value={{value}}
                               {% if sample_idh == value %}
                                 checked=""
                               {% endif %}
                        >
                        <labl style="font-size:{{ value_name_size }}px;"> {{ key }}</labl>
                        <br>
                      {% endfor %}
                    </form>
                  </p>
                </div>
              </div>
            </div>

            <div class="col-xs-12">
              <div class="form-group">
                <!-- DURATION -->
                <div class="col-lg-4 col-md-6 col-sd-12">
                  <label style="font-size:{{ input_title_size }}px;"> {{ duration_title }} </label>
                  <p>
                    <input class="knob" id="duration" data-width="100" data-height="50"
                           data-angleOffset=-90 data-angleArc=180
                           data-fgColor="#34495E" data-rotation="clockwise"
                           data-min={{ min_duration }} data-max={{ max_duration }}
                           value={{ sample_duration }} >
                  </p>
                  <labl> {{ duration_explain }} </labl>
                </div>

                <!-- TDOSE -->
                <div class="col-lg-4 col-md-6 col-sd-12">
                  <label style="font-size:{{ input_title_size }}px;"> {{ tdose_title }} </label>
                  <p>
                    <input class="knob" id="tdose" data-width="100" data-height="120"
                           data-angleOffset=-90 data-angleArc=180
                           data-fgColor="#34495E" data-rotation="clockwise"
                           data-min={{ min_tdose }} data-max={{ max_tdose }}
                           value={{ sample_tdose }} >
                  </p>
                </div>

                <!-- TFX -->
                <div class="col-lg-4 col-md-6 col-sd-12">
                  <label style="font-size:{{ input_title_size }}px;"> {{ tfx_title }} </label>
                  <p>
                    <input class="knob" id="tfx" data-width="100" data-height="120"
                           data-angleOffset=-90 data-angleArc=180
                           data-fgColor="#34495E" data-rotation="clockwise"
                           data-min={{ min_tfx }} data-max={{ max_tfx }}
                           value={{ sample_tfx }} >
                  </p>
                </div>
              </div>
            </div>
            <div class="col-xs-12" id="mri_images">
              {% for key, value in mri_images.items() %}
                <div class="col-md-55">
                  <div class="thumbnail">
                    <div class="image view view-first">
                      <img style="width: 100%; display: block;"
                          src={{ value }} alt="image" />
                    </div>
                    <div class="caption">
                      <p> {{ key }} </p>
                    </div>
                  </div>
                </div>
              {% endfor %}

              <div class="form-group">
                <div class="col-lg-12 col-md-12">
                  <p style="font-size:{{ input_title_size }}px;"> MRI Image </p>
                  {{ dropzone.create(action=url_for('home_blueprint.upload')) }}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-6 col-md-12 col-xs-12">
        <div class="x_panel">
          <div class="x_title">
            <h2>The Probability of Progressive Disease</h2>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
            <div id="{{ chart_id }}" style="width:{{ my_width }};height:{{ my_height }}px;"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

{% block javascripts %}
  {{ super()}}
  <!-- Chart.js -->
  <script src="{{ url_for('static', filename='vendors/Chart.js/dist/Chart.min.js') }}"></script>
  <script src="{{ url_for('static', filename='vendors/echarts/dist/echarts.min.js') }}"></script>
  <!-- jQuery Knob -->
  <script src="{{ url_for('static', filename='vendors/jquery-knob/dist/jquery.knob.min.js') }}"></script>
  <!-- gauge.js -->
  <script src="{{ url_for('static', filename='vendors/gauge.js/dist/gauge.min.js') }}"></script>
  <!-- DateJS -->
  <script src="{{ url_for('static', filename='vendors/DateJS/build/date.js') }}"></script>

  {{ dropzone.load_js() }}
  {{ dropzone.config(
     custom_init='this.on("maxfilesreached",
       function(file) {this.processQueue();});
       this.on("queuecomplete", function(file) {this.removeAllFiles(true);
                                                location.reload();});',
     custom_options='autoProcessQueue: false') }}

  <script>
    window.onload = function() {
      setTimeout(function() {
        var myChart_{{ chart_id }} = echarts.init(document.getElementById('{{ chart_id }}'),
            null, {renderer: '{{ renderer}}'});
        {{ custom_function }}
        var option_{{ chart_id }} = {{ options | safe }};
        myChart_{{ chart_id }}.setOption(option_{{ chart_id }});
        window.onresize = function() {
          myChart_{{ chart_id }}.resize();
        };
      }, 1000);
    };
  </script>
{% endblock javascripts %}